export enum EmotionEnums {
  Angry = "Angry",
  Cheerful = "Cheerful",
  Sad = "Sad",
  Excited = "Excited",
  Friendly = "Friendly",
  Terrified = "Terrified",
  Shouting = "Shouting",
  Unfriendly = "Unfriendly",
  Whispering = "Whispering",
  Hopeful = "Hopeful",
  Soulful = "Soulful",
  Pleasant = "Pleasant",
  Complaining = "Complaining",
  Surprised = "Surprised",
  Uneasy = "Uneasy",
  Fearful = "Fearful",
  Disgust = "Disgust",
}
